Feature sql
StanislavKaisin/Digis-intern-task-backend pull request #7
Opened 2021-11-07 22:24 UTC by StanislavKaisin

2021-11-23 09:22 UTC, sashasemeniuk requested changes

2021-11-23 09:22 UTC, sashasemeniuk commented on src/alerts/alerts.controller.ts
> +    //@ts-ignore
Спробуй найти краще рішення ніж ts ignore

2021-11-23 09:22 UTC, sashasemeniuk commented on src/App/app.module.ts
> +      type: 'sqlite',
Спробуй підняти локально (або не локально, на heroku можна підняти інстанс postgres) якусь бд, а не використовувати sqlite

2021-11-23 09:22 UTC, sashasemeniuk commented on src/alerts/alerts.controller.ts
> +    result.user = [user];
Для чого стільки масивів?

2021-11-23 09:22 UTC, sashasemeniuk commented on src/alerts/alerts.service.ts
> +      const result = {} as any;
Не використовуй any

2021-11-23 23:26 UTC, StanislavKaisin commented on src/App/app.module.ts
> +      type: 'sqlite',
думаю дуже гарна ідея підняти базу окремо. Я тут намагався підняти бекенд в докері, але створення образу падало на встановленні залежностей ".gyp make gcc g++ python". Гугл підказує, що вони потрібні для встановлення та роботи sqlite. Значить, якщо підняти базу окремо та повидаляти з образу бекенду всі залежності sqlite то такої помилки можна уникнути. І так мабуть буде правильніше - щоб база і бекенд були в різних контейнерах (по типу, як mongo db in cloud і бекенд окремо)

2021-12-05 20:38 UTC, StanislavKaisin commented on src/alerts/alerts.controller.ts
> +    result.user = [user];
В цьому місці фронт чекає відповіді, яка в першій версії від монго була з масивами. Щоб не переписувати на фронті компоненти та їх інтерфейси я також повертаю масиви

2022-01-19 22:52 UTC, merged